version: '3.9'
services:
   frontend:
    image: nginx
    container_name: frontend-container
    restart: always
    networks:
      - net-coplandpost
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      # - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/app
      - ./log/nginx/frontend:/var/log/nginx
      # - ./nginx:/etc/nginx


networks:
  net-coplandpost:
    external:
      name: coplandpost-network
volumes:
  frontend-data-vol:
      external: true
      name: frontend-data-vol
